name: right

dynamixel:
  joint_signs: [1, 1, 1, -1, 1, -1, 1, -1]
  joint_ids: [1, 2, 3, 4, 5, 6, 7, 8]
  # ls /dev/serial/by-id/
  dynamixel_port: "/dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FT951EJA-if00-port0"
  
initialization:
  calibration_joint_pos: [-0.1197, 1.8454, -0.0613, -1.2885, -0.1657, 2.5004, -0.0506]
  initial_match_joint_pos: [0.0, -0.7854, 0.0, -2.356, 0.0, 1.57, 0.0, 0.0]

gripper_teleop:
  actuation_range: 0.8

controller:
  torque_feedback:
    enable: True
    gain: 3.0
    motor_scalar: 94.5652173913
  gravity_comp:
    enable: True
    gain: 0.85
  null_space_regulation:
    null_space_joint_target: [0.0, -0.7854, 0.0, -2.356, 0.0, 1.57, 0.0, 0.0]
    kp: 0.1
    kd: 0.01
  static_friction_comp:
    enable_speed: 0.9
    gain: 0.6
  joint_limit_barrier:
    kp: 1.03561658022
    kd: 0.04315069084
  joint_position_control:
    interpolation_step_size: 0.5
    kp: 1.03561658022
    kd: 0.04315069084

  gripper_feedback:
    enable: True
    gain: 0.28328611898


