name: franka_right

dynamixel:
  joint_signs: [1, 1, 1, -1, 1, -1, 1, -1]
  joint_ids: [1, 2, 3, 4, 5, 6, 7, 8]
  # ls /dev/serial/by-id/
  dynamixel_port: "/dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FT951EJA-if00-port0"
  



gripper_teleop:
  actuation_range: 0.8


controller:    

  gravity_comp:
    enable: True
    gain: 0.85
    
  null_space_regulation:
    null_space_joint_target: [0.0, -0.7854, 0.0, -2.356, 0.0, 1.57, 0.0, 0.0]
    kp: 0.2
    kd: 0.01

  static_friction_comp:
    enable_speed: 0.9
    gain: 0.4
  
  joint_limit_barrier:
    kp: 1.03561658022
    kd: 0.04315069084

  joint_position_control:
    interpolation_step_size: 0.5
    kp: 1.03561658022
    kd: 0.04315069084



